'use strict'

//const File = require('../models/file')
const fs = require('fs');


function saveFile(req, res) {
  console.log('POST /api/file')
  console.log(req.body)

  // string generated by canvas.toDataURL()
  var img = req.body.data;
  var imgName = req.body.name;
  var buf = new Buffer(img, 'base64');
  var folder = '';


  if(req.body.type.indexOf('image') !=  -1){    //POSIBLEMENTE HAYA QUE AGREGAR PARA CUANDO SEAN OTROS TIPOS DE ARCHIVOS DISTINTOS A IMG
    switch (req.body.subtype) {
      case 'product':
        folder = 'products/'
        break;
      case 'category':
        folder = 'categories/'
        break;
      case 'menu':
        folder = 'menus/'
        break;
      default:
        break;
    }
  }

  if(folder == ''){
    return res.status(500).send({ message: `El tipo de imagen no es correcto. No se encuentra el directorio de destino.` })
  }
  if(!fs.existsSync(folder)){
    fs.mkdir(folder, { recursive: true }, (err) => {
      if (err) throw err;
    });
  }

  if(!fs.existsSync(folder+imgName)) {
    fs.writeFile(folder + imgName, buf);
    return res;
  }; 

}
module.exports = {
  saveFile,
}
